# Generated by Django 5.1.5 on 2025-04-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroresearch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
