# Generated by Django 5.1.5 on 2025-05-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroresearch', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RainfallData',
        ),
        migrations.DeleteModel(
            name='RainfallScheme',
        ),
    ]
